# Generated by Django 5.0.1 on 2024-04-02 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripapp', '0004_location_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='user',
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.TextField(verbose_name='住所'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=100, verbose_name='名称'),
        ),
    ]
