# Generated by Django 5.0.1 on 2024-04-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripapp', '0007_item_checked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=128)),
                ('detail', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=128, verbose_name='名称'),
        ),
    ]
