# Generated by Django 5.0.1 on 2024-04-15 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripapp', '0009_item_trip_alter_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='trip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tripapp.trip'),
        ),
    ]
