# Generated by Django 5.0.1 on 2024-04-17 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripapp', '0010_alter_item_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
