# Generated by Django 5.0.1 on 2024-05-07 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tripapp', '0013_memo_trip_trip_name_alter_trip_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='name',
        ),
    ]
