# Generated by Django 5.0.1 on 2024-05-10 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripapp', '0014_remove_trip_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='trip',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tripapp.trip'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='picture',
            name='trip',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tripapp.trip'),
            preserve_default=False,
        ),
    ]
