# Generated by Django 5.0.1 on 2024-05-13 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripapp', '0015_location_trip_picture_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='trip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tripapp.trip'),
        ),
        migrations.AlterField(
            model_name='memo',
            name='trip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tripapp.trip'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='trip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tripapp.trip'),
        ),
    ]
